library "jenkins-library"

pipeline {

  agent {
    kubernetes {
      label 'helmfile'
      yamlFile '.jenkins/sidecar.yaml'
      inheritFrom 'default'
    }
  }
  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    skipDefaultCheckout true
  }
  
  stages {
    stage('deploy canary') {
        steps {
            node('helmfile') {
                container('helmfile') {
                script {
                    def cluster = getInfo.namespace('pce0')
                    withAWS(role: getRole(cluster.account).role, roleAccount: getRole(cluster.account).roleAccount) {
                    script {
                        sh "ls /var/jenkins_home/promoter"
                        sh "aws eks update-kubeconfig --name ${cluster.cluster} --region ${cluster.region}"
                        sh "kubectl get namespaces"
                        sh "kubectl get pods -n pce0"
                    }
                    }
                }
                }
            }
        }
    }
  }
}
